openapi: 3.2.0
info:
  description: '# Introduction


    The Monoova PayTo API is designed to efficiently handle real time financial transactions, providing a reliable platform for creating payment agreements and initiating payments.'
  version: v1
  title: Monoova PayTo Initiate a Payment API
  contact:
    name: Monoova Support
    email: support@monoova.com
    url: https://www.monoova.com
  x-logo:
    url: https://movdpwebsiteprodae.blob.core.windows.net/images/Monoova-Primary-Logo-Black-RGB.png
    altText: Monoova logo
servers:
- url: https://api.monoova.com
  description: Production URL#
- url: https://sand-api.monoova.com
  description: Sandbox URL
security:
- BearerAuth: []
tags:
- name: Initiate a Payment
  description: Once a payment agreement is created you can trigger payments against it
paths:
  /au/payto/pas-v1/paymentInstruction:
    post:
      tags:
      - Initiate a Payment
      summary: Payment Instruction
      description: 'Once a valid payment agreement has approved by the payer this endpoint is used to create a payment initiation, which creates real time pull payments.

        You are allowed a maximum of 5 failed initiations in a 24 hour period, if you reach this limit you will need to wait until the next day to retry.'
      operationId: post-paymentinstruction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiateMandatePaymentDto'
            example:
              paymentAgreementUID: BCORP123456
              paymentInitiationUID: BCORP00000001
              paymentDetails:
                amount: 1.0
                lodgementReference: BCorp PIR 001
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateMandatePaymentResponseDto'
        '202':
          description: pending
          content:
            application/json:
              example:
                paymentAgreementUID: '1111222333'
                paymentInitiationUID: C150D6FAE2044CA9A3ADB470874E8F86
                mmsId: ed8569b4fd8614259d13bcb9a2da2bc0
                nppInstructionId: MOPYAUS1XXXI20241119004756058205270
                paymentInitiationStatus: INPR
                paymentInitiationStatusDescription: In progress
                traceId: f3ae20c5-e400-4eab-8fb0-16e03c8481be
        '422':
          description: Rejected
          content:
            application/json:
              example:
                paymentAgreementUID: '1111222333'
                paymentInitiationUID: C150D6FAE2044CA9A3ADB470874E8F86
                mmsId: ed8469b4fd8616259d15b4b9a2da2bc0
                paymentInitiationStatus: RJCT
                paymentInitiationStatusDescription: Rejected
                statusReasonCode: R999
                statusReasonDescription: Payment initiation rejected by banking institution. Please contact Monoova
                traceId: f3ae20c5-e400-4eab-8fb0-16e03c8481be
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
components:
  schemas:
    InitiateMandatePaymentDto:
      type: object
      required:
      - paymentAgreementUID
      - paymentInitiationUID
      - paymentDetails
      properties:
        paymentAgreementUID:
          type:
          - string
          - 'null'
          maxLength: 35
          description: Id to uniquely Identify a payment agreement.
        paymentInitiationUID:
          type:
          - string
          - 'null'
          maxLength: 35
          description: Id to uniquely identify payment
        payeeDetails:
          $ref: '#/components/schemas/PayeeDetailsDto'
        paymentDetails:
          $ref: '#/components/schemas/PaymentInitiationDetailsDto'
      additionalProperties: false
    PaymentInitiationDetailsDto:
      type: object
      required:
      - amount
      properties:
        amount:
          type: string
          description: Amount to be transferred. Amount should be >=0.01
          maxLength: 34
        isLastPayment:
          type:
          - boolean
          - 'null'
          description: Set to true to indicate this is the last payment initiation request associated with the mandate. Possible values - True, False.
        lodgementReference:
          type:
          - string
          - 'null'
          description: Unique reference, as assigned by the creditor, to unambiguously refer to the payment transaction.
          maxLength: 280
      additionalProperties: false
    PayeeDetailsDto:
      required:
      - payeeType
      oneOf:
      - required:
        - payeeLinkedBsb
        - payeeLinkedAccount
      - required:
        - payeeLinkedPayId
        - payeeLinkedPayIdType
        - payeeAccountName
      type: object
      properties:
        payeeType:
          type:
          - string
          - 'null'
          description: Identifies the type of a party.</br> Possible Values ORGN - Organization, PERS - Person
          example: ORGN
        payeeLinkedBsb:
          type:
          - string
          - 'null'
          description: BSB number. </br>Required if 'payeeLinkedPayId' and 'payeeLinkedPayIdType' are not provided. e.g. '999-999 or 999999'
          example: 999-999
        payeeLinkedAccount:
          type:
          - string
          - 'null'
          maxLength: 28
          description: Bank Account Number. </br>Required if 'payeeLinkedPayId' and 'payeeLinkedPayIdType' are not provided.
          example: 22222222
        payeeLinkedPayId:
          type:
          - string
          - 'null'
          description: PayID. </br> Email, phone number, ABN, ACN or Organisation name. </br>Required if 'payeeLinkedBsb' and 'payeeLinkedAccount' are not provided. <a href="/payTo#tag/PAYID-Format-Validation">See PAYID Format Validation.</a>
          example: ''
        payeeLinkedPayIdType:
          type:
          - string
          - 'null'
          description: PayID Type. Possible values ABN, Email, PhoneNumber, OrganisationId, ACN. </br>Required if 'payeeLinkedBsb' and 'payeeLinkedAccount' are not provided.
          example: ''
        payeeAccountName:
          type:
          - string
          - 'null'
          description: Bank Account Name </br> Can only provide payeeAccountName in the payload if crediting an external BSB. Mandatory if crediting a PayID.
          maxLength: 140
          example: ABCORP
        ultimatePayee:
          type:
          - string
          - 'null'
          example: ABCORP
          description: Name by which the party is known, and which is usually used to identify that party.</br> Can only provide ultimatePayee in the payload if crediting an external BSB.
      additionalProperties: false
    InitiateMandatePaymentResponseDto:
      type: object
      properties:
        traceId:
          type: string
          example: f3ae20c5-e400-4eab-8fb0-16e03c8481be
        paymentAgreementUID:
          type: string
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Z0-9_-]
          example: MOA1222333
        paymentInitiationUID:
          type: string
          description: Id to uniquely Identify a payment initiation.
          maxLength: 35
          pattern: ^[A-Z0-9_-]
          example: C150D6FAE2044CA9A3ADB470874E8F86
        nppInstructionId:
          type: string
          description: Unique identifier for the NPP instruction.
          maxLength: 35
          example: MOPYAUS1XXXI20241119004756058205270
        paymentInitiationStatus:
          type: string
          description: This is the status of the payment agreement.
          example: ACSC
        paymentInitiationStatusDescription:
          type: string
          description: This describes the status. For example, a status of ‘created’ will have a description of ‘Pending Payer Approval’
          example: Accepted & Settled
        mmsId:
          type: string
          description: This is the unique ID that identifies this payment agreement.
          example: ed8569b5fd8616259d15b5b9a2d52bc0
      additionalProperties: false
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic
x-tagGroups:
- name: ''
  tags:
  - Generate a Bearer Token
  - Manage Payment Agreements
  - PayTo Async API
  - Initiate a Payment
  - Reporting
  - Webhooks
  - Notification Management
  - PAYID Format Validation
  - Client Error Responses
  - Monoova Error Codes
  - Mandate Status Reason Codes
  - Payment Initiation Status
  - Payment Agreement Status
  - Payment Initiation Reject Reason Codes
