openapi: 3.2.0
info:
  description: '# Introduction

    Monoova''s Online Card Payment Service incorporates a next-gen Card Payment Checkout integrated with our expansive Payments API to allow merchants to capture card and mobile wallet payments from your customers online and receive funds into your Monoova account for automated reconciliation and disbursement.'
  version: v1
  title: Monoova Card Payments Create Payment Using Token API
  contact:
    name: Monoova Support
    email: support@monoova.com
    url: https://www.monoova.com
  x-logo:
    url: https://movdpwebsiteprodae.blob.core.windows.net/images/Monoova-Primary-Logo-Black-RGB.png
    altText: Monoova logo
servers:
- url: https://api.monoova.com
  description: Production URL#
- url: https://sand-api.monoova.com
  description: Sandbox URL
security:
- BearerAuth: []
tags:
- name: Create Payment Using Token
paths:
  /au/card/ccm/CreditCardTransaction/payment:
    post:
      tags:
      - Create Payment Using Token
      summary: Create a Payment using Token
      description: This endpoint is used to create payments using tokens.
      operationId: createPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentRequest'
            example:
              clientTransactionUniqueReference: 6aac85b115c7405180e6c7a7735c9f3c
              customer:
                customerId: '12345678'
                billingAddress:
                  firstName: Joseph
                  lastName: Blogs
                  street:
                  - 1 Walker St
                  suburb: North Sydney
                  state: NSW
                  postalCode: '2000'
                  countryCode: AU
                emailAddress: joe.blogs@monoova.com
              paymentDetails:
                clientPaymentTokenUniqueReference: Token123
                description: sample token create
              amount:
                currencyAmount: 100.0
      responses:
        '201':
          description: Accepted by gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
              example:
                traceId: 1dabfaa9-abe8-4d2d-a69a-b723079d84ed
                clientTransactionUniqueReference: DCCCC5DE-CC48-4942-A419-F1B84EC122C4
                clientPaymentTokenUniqueReference: TOKEN123
                status: Pending Settlement
        '200':
          description: Declined by gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
              example:
                traceId: 1dabfaa9-abe8-4d2d-a69a-b723079d84ed
                clientTransactionUniqueReference: DCCCC5DE-CC48-4942-A419-F1B84EC122C4
                clientPaymentTokenUniqueReference: TOKEN123
                status: Declined
                statusReasonCode: reasonCode
                statusReasonDescription: reasonDescription
        '400':
          description: Invalid request
          content:
            application/json:
              example:
                traceId: 0d4518e0-8934-489c-b303-1f82323f2595
                errors:
                - errorCode: CCM_ACC_LIMIT_REACHED
                  errorMessage: transaction amount 100.00 plus existing transactions 100.00 exceeds limit 50
components:
  schemas:
    CreatePaymentRequest:
      type: object
      required:
      - clientTransactionUniqueReference
      - customer
      - paymentDetails
      - amount
      properties:
        clientTransactionUniqueReference:
          type: string
          description: This id will be used to uniquely identify each payment request made by our customer
          pattern: ^[a-zA-Z0-9_-]{1,40}$
        customer:
          type: object
          required:
          - customerId
          properties:
            customerId:
              type: string
              description: Value to uniquely identify a customer
              pattern: ^[a-zA-Z0-9_-]{1,16}$
            billingAddress:
              type: object
              required:
              - firstName
              - lastName
              - street
              - suburb
              - state
              - postalCode
              - countryCode
              properties:
                firstName:
                  type: string
                  maxLength: 60
                lastName:
                  type: string
                  maxLength: 60
                street:
                  type: array
                  items:
                    type: string
                    maxLength: 60
                  minItems: 1
                  maxItems: 2
                suburb:
                  type: string
                  maxLength: 14
                state:
                  type: string
                  maxLength: 3
                postalCode:
                  type: string
                  maxLength: 14
                countryCode:
                  type: string
                  pattern: ^[A-Z]{2}$
            emailAddress:
              type: string
              format: email
              maxLength: 40
        paymentDetails:
          type: object
          required:
          - clientPaymentTokenUniqueReference
          - description
          properties:
            clientPaymentTokenUniqueReference:
              type: string
              pattern: ^[a-zA-Z0-9_-]{1,40}$
            description:
              type: string
              maxLength: 40
        amount:
          type: object
          required:
          - currencyAmount
          properties:
            currencyAmount:
              type: number
              format: decimal
              maximum: 20000000.0
    PaymentResponse:
      type: object
      required:
      - traceId
      - clientTransactionUniqueReference
      - clientPaymentTokenUniqueReference
      - status
      properties:
        traceId:
          type: string
          description: Unique identifier for logging
        clientTransactionUniqueReference:
          type: string
          description: Unique identifier for each payment request
        clientPaymentTokenUniqueReference:
          type: string
          description: Token against which Payment should be created
        status:
          type: string
          description: Current status of the transaction
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic
x-tagGroups:
- name: ''
  tags:
  - Generate a Bearer Token
  - Generate a Client Session
  - Get Transaction By Id
  - Get Transaction By Date Range
  - Request Refund Transaction
  - Get Async Request Status
  - Create Payment Using Token
  - Get Payment Method Token Details
  - Update Payment Method Token Status
  - Webhooks
  - Monoova Error Codes
