openapi: 3.2.0
info:
  description: '# Introduction


    The Monoova PayTo API is designed to efficiently handle real time financial transactions, providing a reliable platform for creating payment agreements and initiating payments.'
  version: v1
  title: Monoova PayTo PayTo Async API
  contact:
    name: Monoova Support
    email: support@monoova.com
    url: https://www.monoova.com
  x-logo:
    url: https://movdpwebsiteprodae.blob.core.windows.net/images/Monoova-Primary-Logo-Black-RGB.png
    altText: Monoova logo
servers:
- url: https://api.monoova.com
  description: Production URL#
- url: https://sand-api.monoova.com
  description: Sandbox URL
security:
- BearerAuth: []
tags:
- name: PayTo Async API
  description: The `AsyncResponse` is used in operations where the request is accepted, but the processing is not immediate.
paths:
  /au/payto/pam-v1/PaymentAgreementAsync/Request/{uniqueRequestId}:
    get:
      tags:
      - PayTo Async API
      summary: Get Async Payment Agreement Request Status
      description: Queries the status of an asynchronous API request for creating a payment agreement. This endpoint requires the {uniqueRequestId} returned by the original Async API call. There is no request body.
      operationId: get-async-paymentagreement-status
      parameters:
      - name: uniqueRequestId
        in: path
        required: true
        schema:
          type: string
          description: Unique identifier returned by the original Async API call.
          example: 4834dba5-27b0-465c-aea7-aa530315c68c
      responses:
        '200':
          description: Request is still processing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingAgreementAsyncResponse'
        '201':
          description: Successful completion. The Location header contains the URL for the updated resource/document.
          headers:
            Location:
              schema:
                type: string
              description: URL to be polled for the updated resource/document.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessAgreementAsyncResponse'
        '400':
          description: Invalid status request.
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '422':
          description: Background job has failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncMandateRequestFailedResponse'
  /au/payto/pas-v1/PaymentInstructionAsync/Request/{uniqueRequestId}:
    get:
      tags:
      - PayTo Async API
      summary: Get Async Payment Instruction Request Status
      description: Queries the status of an asynchronous API request, such as "Initiate Payment Async". This endpoint requires the {uniqueRequestId} returned by the original Async API call. No request body is needed.
      operationId: get-async-paymentinitiation-status
      parameters:
      - name: uniqueRequestId
        in: path
        required: true
        schema:
          type: string
          description: Unique identifier returned by the original Async API call.
          example: 4834dba5-27b0-465c-aea7-aa530315c68c
      responses:
        '200':
          description: Request is still processing.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PendingInitiationAsyncResponse'
        '201':
          description: Successful completion. Location header contains the URL for the updated resource/document.
          headers:
            Location:
              schema:
                type: string
              description: URL to be polled for the updated resource/document.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessInitiationAsyncResponse'
        '400':
          description: Invalid status request.
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '422':
          description: Background job has failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncInitiationRequestFailedResponse'
  /au/payto/pam-v1/PaymentAgreementAsync:
    post:
      tags:
      - PayTo Async API
      summary: Create a Payment Agreement Async
      description: 'The purpose of this endpoint is to asynchronously create a payment agreement. The API returns as soon as the creation request has been captured and validated for background processing.


        The async API follows the Microsoft async-request-reply pattern.


        Following a successful call, the status of the background request can be monitored using Get Async Request Status (Payment Instruction) or by subscription to the AsyncJobResultNotification webhook.


        The background request will complete when the payment agreement is either:

        - Created (Note: This does not necessarily mean the payment agreement has been activated.)

        - Failing with a non-recoverable error (retries will occur for transient errors such as timeouts)

        - Timed out on retries (set to 4 days).


        After request completion, the status of the payment agreement can be determined by calling Get Payment Agreement by UniqueId or by subscription to the PaymentAgreementNotification webhook.

        The request payload and business rules/validations are identical to the synchronous API.'
      operationId: post-paymentagreement-async
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentAgreementDto'
      responses:
        '202':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncGenericResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pas-v1/PaymentInstructionAsync:
    post:
      tags:
      - PayTo Async API
      summary: Create Payment Instruction Async
      description: 'The purpose of this endpoint is to asynchronously create a payment instruction. The API returns as soon as the creation request has been captured and validated for background processing.


        The async API follows the Microsoft async-request-reply pattern.


        Following a successful call, the status of the background request can be monitored using the Get Async Request Status (Payment Instruction) endpoint or by subscription to the AsyncJobResultNotification webhook.


        The background request will complete when the payment instruction is either:

        - Created (This does not necessarily mean the payment has already been finalized).

        - Failing with a non-recoverable error. The background request will do retries for transient errors such as timeouts.

        - Timed out on retries (set to 4 days).


        After request completion, the status of the payment can be determined by calling Get Payment Instruction By UniqueId or by subscription to the Get Payment Instruction By UniqueId webhook.


        The request payload and business rules/validations are identical to the synchronous API.'
      operationId: post-async-paymentinstruction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiateMandatePaymentDto'
            example:
              paymentAgreementUID: BCORP123456
              paymentInitiationUID: BCORP00000001
              paymentDetails:
                amount: 1.0
                lodgementReference: BCorp PIR 001
      responses:
        '202':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncGenericResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pam-v1/PaymentAgreementAsync/{paymentAgreementUID}/unilateral:
    patch:
      tags:
      - PayTo Async API
      summary: Unilateral Amendment Async
      description: 'The purpose of this endpoint is to asynchronously amend a payment agreement that does not require approval from the Payer. The API returns as soon as the amend request has been captured and validated for background processing.

        The request payload and business rules/validations are identical to the synchronous API.'
      operationId: patch-async-paymentagreement-id-unilateral
      parameters:
      - name: paymentAgreementUID
        in: path
        required: true
        schema:
          type:
          - string
          - 'null'
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Za-z0-9_-]
          example: MONPAG12345
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/AmendUnilateralDetailsDto'
            example:
              description: payroll pag1
              shortDescription: payroll pag1
              payeeDetails:
                payeeType: ORGN
                payeeLinkedBsb: 802980
                payeeLinkedAccount: 33333333
                payeeLinkedPayId: abc@gmail.com
                payeeLinkedPayIdType: EMAIL
                payeeAccountName: PayCo
                ultimatePayee: PayCo
      responses:
        '202':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncGenericResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: b008558d-b6df-4935-b2aa-39b2f8d467be
                errors:
                - errorCode: PAM_BR_AMEND_FORBIDDEN
                  errorMessage: Can only amend payment agreement in active or paused status
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pam-v1/PaymentAgreementAsync/{paymentAgreementUID}/bilateral:
    patch:
      tags:
      - PayTo Async API
      summary: Bilateral Amendment Async
      operationId: patch-async-paymentagreement-id-bilateral
      description: 'The purpose of this endpoint is to asynchronously amend a payment agreement which requires approval from the Payer. Changes made using this end point will only get reflected after payer approves the change. The API returns as soon as the amend request has been captured and validated for background processing.

        The request payload and business rules/validations are identical to the synchronous API.'
      parameters:
      - name: paymentAgreementUID
        in: path
        required: true
        schema:
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Za-z0-9_-]
          example: MONPAG12345
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmendBilateralDetailsDto'
      responses:
        '202':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncGenericResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pam-v1/PaymentAgreementAsync/{paymentAgreementUID}/status:
    patch:
      tags:
      - PayTo Async API
      summary: Amend Payment Agreement Status Async
      description: 'This endpoint allows the initiator to change the status of a payment agreement. Available statuses are active, pause or cancel. The API returns as soon as the amend request has been captured and validated for background processing.

        The request payload and business rules/validations are identical to the synchronous API.'
      operationId: patch-async-paymentagreement-id-status
      parameters:
      - name: paymentAgreementUID
        in: path
        required: true
        schema:
          type:
          - string
          - 'null'
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Za-z0-9_-]
          example: MONPAG12345
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmendPaymentAgreementStatusDto'
            example:
              statusChange: pause
              reasonCode: AC02
              reasonDescription: Amend mandate status
      responses:
        '202':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncGenericResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pam-v1/PaymentAgreementAsync/{PaymentAgreementUID}/recall/{actionIdentification}:
    patch:
      tags:
      - PayTo Async API
      summary: Recall a Payment Agreement Async
      description: 'The purpose of this endpoint is to asynchronously recall a pending PAG creation/amendment action before it is approved or declined by payer servicer/customer. We will cancel the action uniquely identified by actionIdentification. The API returns as soon as the recall request has been captured and validated for background processing.

        The request payload and business rules/validations are identical to the synchronous API.'
      operationId: patch-async-paymentagreement-id-recall
      parameters:
      - name: PaymentAgreementUID
        in: path
        required: true
        schema:
          type: string
          maxLength: 35
          pattern: ^[A-Za-z0-9_-]
          description: Id to uniquely Identify a payment agreement.
          example: MONPAG12345
      - name: actionIdentification
        in: path
        required: true
        schema:
          type: string
          maxLength: 35
          pattern: ^[a-f0-9]{12}1[a-f0-9]{3}[89ab][a-f0-9]{15}$
          description: unique Id used to identify pending(unapproved) actions. This id is assigned when a new payment agreement is created or when a bilateral amendment is made.
          example: 6ae818a80ba362618aeaece46ee70e4a
      responses:
        '202':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncGenericResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
components:
  schemas:
    PendingAgreementAsyncResponse:
      type: object
      properties:
        traceId:
          type: string
          description: Trace identifier.
          example: be393fae-52c2-4c9e-a262-4974de6da750
        uniqueRequestId:
          type: string
          description: Server generated unique request identifier.
          example: 4834dba5-27b0-465c-aea7-aa530315c68c
        paymentAgreementUID:
          type: string
          description: User supplied PAG identifier.
          example: MONPAG1673935776
        status:
          type: string
          description: Current status of the request.
          example: Processing
    SuccessAgreementAsyncResponse:
      type: object
      properties:
        traceId:
          type: string
          description: Error log trace identifier.
          example: c0905f60-80b7-4a6a-abe3-0207b3e19b8e
        uniqueRequestId:
          type: string
          description: Server generated unique request identifier.
          example: 595a3202-e9aa-406e-a2a3-5efb6ca8b72a
        paymentAgreementUID:
          type: string
          description: User supplied PAG identifier.
          example: MONPAG1673930138
        status:
          type: string
          description: Final status of the request.
          example: Completed
    SuccessInitiationAsyncResponse:
      type: object
      properties:
        traceId:
          type: string
          description: Error log trace identifier.
          example: c0905f60-80b7-4a6a-abe3-0207b3e19b8e
        uniqueRequestId:
          type: string
          description: Server generated unique request identifier.
          example: 595a3202-e9aa-406e-a2a3-5efb6ca8b72a
        paymentInitiationUID:
          type: string
          description: User supplied PIR identifier.
          example: MONPIR1673930138
        status:
          type: string
          description: Final status of the request.
          example: Completed
    PayerDetailsDto:
      type: object
      required:
      - payerType
      - payer
      - ultimatePayer
      - payerPartyReference
      oneOf:
      - required:
        - linkedBsb
        - linkedAccount
      - required:
        - linkedPayId
        - linkedPayIdType
      properties:
        payerType:
          type:
          - string
          - 'null'
          description: Identifies the type of party. </br> Possible Values - ORGN (Organization),    PERS (Person)
          example: ORGN
        linkedBsb:
          type:
          - string
          - 'null'
          description: BSB (Bank-State-Branch) number. </br>Required if 'linkedPayId' and 'linkedPayIdType' are not provided.
          example: 802950
        linkedAccount:
          type:
          - string
          - 'null'
          description: Bank account number. </br>Required if 'linkedPayId' and 'linkedPayIdType' are not provided.
          maxLength: 28
          example: 10109010
        linkedPayId:
          type:
          - string
          - 'null'
          example: null
          description: PayID. </br> Email, phone number, ABN, ACN or Organisation ID. </br>Required if 'linkedBsb' and 'linkedAccount' are not provided. <a href="/payTo#tag/PAYID-Format-Validation">See PAYID Format Validation.</a>
        linkedPayIdType:
          type:
          - string
          - 'null'
          example: null
          description: PayID Type. </br>Possible Values - Email, PhoneNumber, ABN, ACN, OrganisationId. </br>Required if 'linkedBsb' and 'linkedAccount' are not provided.
        payer:
          type:
          - string
          - 'null'
          description: Bank Account Name.
          maxLength: 140
          example: ABCCORPCo
        ultimatePayer:
          type:
          - string
          - 'null'
          maxLength: 140
          description: Name by which the party is known, and which is usually used to identify that party.
          example: ABCCORPCo
        payerPartyReference:
          type:
          - string
          - 'null'
          maxLength: 35
          description: This field will be presented to Payer in the detail agreement view. This field also be used group payment initiations associated with a payment agreement.
          example: Payer54321
      additionalProperties: false
    InitiateMandatePaymentDto:
      type: object
      required:
      - paymentAgreementUID
      - paymentInitiationUID
      - paymentDetails
      properties:
        paymentAgreementUID:
          type:
          - string
          - 'null'
          maxLength: 35
          description: Id to uniquely Identify a payment agreement.
        paymentInitiationUID:
          type:
          - string
          - 'null'
          maxLength: 35
          description: Id to uniquely identify payment
        payeeDetails:
          $ref: '#/components/schemas/PayeeDetailsDto'
        paymentDetails:
          $ref: '#/components/schemas/PaymentInitiationDetailsDto'
      additionalProperties: false
    PaymentInitiationDetailsDto:
      type: object
      required:
      - amount
      properties:
        amount:
          type: string
          description: Amount to be transferred. Amount should be >=0.01
          maxLength: 34
        isLastPayment:
          type:
          - boolean
          - 'null'
          description: Set to true to indicate this is the last payment initiation request associated with the mandate. Possible values - True, False.
        lodgementReference:
          type:
          - string
          - 'null'
          description: Unique reference, as assigned by the creditor, to unambiguously refer to the payment transaction.
          maxLength: 280
      additionalProperties: false
    AmendPaymentAgreementStatusDto:
      type: object
      properties:
        paymentAgreementUID:
          type: string
          description: 'Unique ID of the payment agreement.

            '
        statusChange:
          type: string
          description: The status that you wish to change the payment agreement to. </br> <strong> Note&#58;</strong> You cannot change a status from ‘Created’ to ‘Cancel’. If you wish to recall a payment agreement before the payer has approved it, you need to use the Recall Agreement endpoint.</b> </br> <style type="text/css"> .tb { table-layout:auto; width:300px;!important } .td { overflow:hidden; white-space:nowrap; text-overflow:ellipsis!important} </style> <table class="tb"> <tr> <th> Current Status </th> <th> Payload Status </th> <th> New Status </th> <th> Note </th> </tr> <tr><td>    Active    </td><td>    Cancel    </td> <td>    Cancelled    </td><td>    Reason Code is mandatory.    </td></tr> <tr><td>    Active     </td><td>    Pause    </td><td>    Paused    </td><td>    Reason Code is mandatory.    </td></tr> <tr><td>    Paused    </td><td>    Resume    </td><td>    Active    </td><td>    Only party who suspended can Activate payment agreement    </td></tr> <tr><td>    Paused    </td><td>    Cancel    </td><td>    Cancelled    </td><td>    Reason Code is mandatory.    </td></tr> <tr><td>    Cancel    </td><td>-</td><td>-</td><td>    This is the final status    </td></tr> </table>
        reasonCode:
          type: string
          description: 'Reason code for changing the agreement status. Must be provided when the status is `Cancel` or `Pause`.

            '
          example: AC02
        reasonDescription:
          type: string
          description: 'Description of the reason for the change in status.

            '
          example: Invalid Debtor Account Number
          maxLength: 256
    AsyncInitiationRequestFailedResponse:
      type: object
      properties:
        traceId:
          type: string
          description: Error log trace identifier.
          example: c0905f60-80b7-4a6a-abe3-0207b3e19b8e
        uniqueRequestId:
          type: string
          description: Server generated unique request identifier.
          example: 595a3202-e9aa-406e-a2a3-5efb6ca8b72a
        paymentInitiationUID:
          type: string
          description: User supplied PIR identifier.
          example: MONPIR1673930138
        status:
          type: string
          description: Final status of the request indicating failure.
          example: Failed
        errorCode:
          type: string
          description: Error code indicating the reason for failure.
          example: MOV_UNEXPECTED_VALIDATION_FAILURE
        errorMessage:
          type: string
          description: Detailed message explaining the reason for failure.
          example: Validation failed with banking partner. Contact Monoova for more information
    AmendBilateralDetailsDto:
      type: object
      properties:
        automaticRenewal:
          type:
          - boolean
          - 'null'
        endDate:
          type:
          - string
          - 'null'
          description: End date of the validity of the mandate. If specified, the mandate is valid until 23:59:59.999 Australia Sydney time on this date.
        respondByTime:
          type:
          - string
          - 'null'
          format: date-time
          description: Optional time used to indicate by when resolution of a bilateral action is requested from the other party to the payment agreement. It will be provided in any notification sent to the counterparty. This time is for informational purposes only and does not affect the expiry time imposed by the MMS. Must be future date and less than 5 days If not provided value will be defaulted to agreement creation datetime + 5 day Default time zone is UTC
        paymentTerms:
          $ref: '#/components/schemas/PaymentTermsDto'
      additionalProperties: false
    PaymentTermsDto:
      required:
      - numberOfTransactionsPermitted
      - frequency
      - amount
      - agreementType
      type: object
      properties:
        numberOfTransactionsPermitted:
          type:
          - integer
          - 'null'
          format: int32
          description: Quantifies the number of transactions allowed per frequency
          example: 10
        frequency:
          type:
          - string
          - 'null'
          description: Specifies the regularity of an event. See Frequency Table for allowed values
          example: WEEK
        pointInTime:
          type:
          - number
          - 'null'
          description: Qualifies the frequency in terms of an exact point in time or moment within the specified period.</br> Valid non decimal numeric value. Supported values will be 01 to 31 </br> This field works in combination with frequency and can only be provided when frequency = MNTH </br> This field should not be provided if numberOfTransactionsPermitted is provided
          example: null
        amount:
          type:
          - number
          - 'null'
          maxLength: 34
          example: null
          description: Exact amount that may be paid from the Creditor's account, per instruction. Refer to AgreementType & Amount table below
        maximumAmount:
          type:
          - number
          - 'null'
          maxLength: 34
          example: 100.0
          description: Maximum amount that may be paid from the Creditor's account, per instruction. Refer to AgreementType & Amount table below
        agreementType:
          type:
          - string
          - 'null'
          description: Based on the AgreementType table
          example: VARI
      additionalProperties: false
    AsyncMandateRequestFailedResponse:
      type: object
      properties:
        traceId:
          type: string
          description: Error log trace identifier.
          example: c0905f60-80b7-4a6a-abe3-0207b3e19b8e
        uniqueRequestId:
          type: string
          description: Server generated unique request identifier.
          example: 595a3202-e9aa-406e-a2a3-5efb6ca8b72a
        paymentAgreementUID:
          type: string
          description: User supplied PAG identifier.
          example: MONPAG1673930138
        status:
          type: string
          description: Final status of the request indicating failure.
          example: Failed
        errorCode:
          type: string
          description: Error code indicating the reason for failure.
          example: MOV_UNEXPECTED_VALIDATION_FAILURE
        errorMessage:
          type: string
          description: Detailed message explaining the reason for failure.
          example: Validation failed with banking partner. Contact Monoova for more information
    PaymentDetailsDto:
      required:
      - automaticRenewal
      - purpose
      - startDate
      properties:
        automaticRenewal:
          type:
          - boolean
          - 'null'
          example: false
          description: Determines if the payment agreement automatically renews at the end of the defined period. </br> Possible values - True, False </br> endDate cannot be present if automaticRenewal is set as 'TRUE', endDate must be present if automaticRenewal is set as 'FALSE'
        description:
          type:
          - string
          - 'null'
          description: Reason for the mandate setup as narrative text. </br> Either "description" or "short_description" must be present
          maxLength: 140
          example: null
        shortDescription:
          description: Reason for the mandate setup as narrative text. </br> Either "description" or "short_description" must be present
          type:
          - string
          - 'null'
          maxLength: 35
          example: PayToTest_001
        purpose:
          type:
          - string
          - 'null'
          description: Payment Purpose Code. </br>  Possible Values- </br>  MORT - Mortgage Payments </br>  UTIL - Utility Payments </br>  LOAN - Loan Payments </br>  DEPD - Dependant Support Payments </br>  GAMP - Gambling Payments </br>  RETL - Retail Payments </br>  SALA - Salary Payments </br>  PERS - Personal Payment </br>  GOVT - Government Payments </br>  PENS - Pension Payments </br>  TAXS - Tax Payments </br>  OTHR - Other Service Payments
          example: MORT
        respondByTime:
          type:
          - string
          - 'null'
          description: Optional time used to indicate by when resolution of a bilateral action is requested from the other party to the payment agreement. It will be provided in any notification sent to the counterparty. This time is for informational purposes only and does not affect the expiry time imposed by the MMS.<br/>Must be future date and less than 5 days<br/> If not provided value will be defaulted to agreement creation datetime + 5 day<br/> Default time zone is UTC
          format: ISODateTime ( yyyy-mm-ddThh:mm:ss+|–hh:mm)
          example: 2022-09-13 14:35:27+00:00
        startDate:
          description: Start date of the validity of the mandate. The mandate is valid as of 00:00:00.000 Australia Sydney time on this date.
          type:
          - string
          - 'null'
          format: YYYY-MM-DD
          example: 2022-09-13
        endDate:
          type:
          - string
          - 'null'
          format: YYYY-MM-DD
          example: 2023-08-24
          description: End date of the validity of the mandate. If specified, the mandate is valid until 23:59:59.999 Australia Sydney time on this date.
      additionalProperties: false
    PendingInitiationAsyncResponse:
      type: object
      properties:
        traceId:
          type: string
          description: Error log trace identifier.
          example: be393fae-52c2-4c9e-a262-4974de6da750
        uniqueRequestId:
          type: string
          description: Server generated unique request identifier.
          example: 4834dba5-27b0-465c-aea7-aa530315c68c
        paymentInitiationUID:
          type: string
          description: User supplied PIR identifier.
          example: MONPIR1673935776
        status:
          type: string
          description: Current status of the request.
          example: Processing
    PayeeDetailsDto:
      required:
      - payeeType
      oneOf:
      - required:
        - payeeLinkedBsb
        - payeeLinkedAccount
      - required:
        - payeeLinkedPayId
        - payeeLinkedPayIdType
        - payeeAccountName
      type: object
      properties:
        payeeType:
          type:
          - string
          - 'null'
          description: Identifies the type of a party.</br> Possible Values ORGN - Organization, PERS - Person
          example: ORGN
        payeeLinkedBsb:
          type:
          - string
          - 'null'
          description: BSB number. </br>Required if 'payeeLinkedPayId' and 'payeeLinkedPayIdType' are not provided. e.g. '999-999 or 999999'
          example: 999-999
        payeeLinkedAccount:
          type:
          - string
          - 'null'
          maxLength: 28
          description: Bank Account Number. </br>Required if 'payeeLinkedPayId' and 'payeeLinkedPayIdType' are not provided.
          example: 22222222
        payeeLinkedPayId:
          type:
          - string
          - 'null'
          description: PayID. </br> Email, phone number, ABN, ACN or Organisation name. </br>Required if 'payeeLinkedBsb' and 'payeeLinkedAccount' are not provided. <a href="/payTo#tag/PAYID-Format-Validation">See PAYID Format Validation.</a>
          example: ''
        payeeLinkedPayIdType:
          type:
          - string
          - 'null'
          description: PayID Type. Possible values ABN, Email, PhoneNumber, OrganisationId, ACN. </br>Required if 'payeeLinkedBsb' and 'payeeLinkedAccount' are not provided.
          example: ''
        payeeAccountName:
          type:
          - string
          - 'null'
          description: Bank Account Name </br> Can only provide payeeAccountName in the payload if crediting an external BSB. Mandatory if crediting a PayID.
          maxLength: 140
          example: ABCORP
        ultimatePayee:
          type:
          - string
          - 'null'
          example: ABCORP
          description: Name by which the party is known, and which is usually used to identify that party.</br> Can only provide ultimatePayee in the payload if crediting an external BSB.
      additionalProperties: false
    AsyncGenericResponse:
      type: object
      properties:
        traceId:
          type: string
          description: Unique identifier for this request instance, useful for tracing.
          example: ac819ad0-c3ee-44f9-964a-34a0a5ff5a24
        uniqueRequestId:
          type: string
          description: Unique identifier assigned to the request to correlate with the response.
          example: 595a3202-e9aa-406e-a2a3-5efb6ca8b72a
    AmendUnilateralDetailsDto:
      type: object
      properties:
        description:
          type:
          - string
          - 'null'
          description: Reason for the mandate setup as narrative text.</br> Either "description" or "short_description" must be present.
          maxLength: 140
          example: payroll pag1
        shortDescription:
          type:
          - string
          - 'null'
          description: Reason for the mandate setup as narrative text.</br> Either "description" or "short_description" must be present.
          maxLength: 35
          example: payroll pag1
        payeeDetails:
          $ref: '#/components/schemas/PayeeDetailsDto'
      additionalProperties: false
    CreatePaymentAgreementDto:
      type: object
      required:
      - paymentAgreementUID
      properties:
        paymentAgreementUID:
          type: string
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Z0-9_-]
          example: ABCORP123456
        payeeDetails:
          $ref: '#/components/schemas/PayeeDetailsDto'
        payerDetails:
          $ref: '#/components/schemas/PayerDetailsDto'
        paymentTerms:
          $ref: '#/components/schemas/PaymentTermsDto'
        paymentDetails:
          $ref: '#/components/schemas/PaymentDetailsDto'
      additionalProperties: false
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic
x-tagGroups:
- name: ''
  tags:
  - Generate a Bearer Token
  - Manage Payment Agreements
  - PayTo Async API
  - Initiate a Payment
  - Reporting
  - Webhooks
  - Notification Management
  - PAYID Format Validation
  - Client Error Responses
  - Monoova Error Codes
  - Mandate Status Reason Codes
  - Payment Initiation Status
  - Payment Agreement Status
  - Payment Initiation Reject Reason Codes
