openapi: 3.2.0
info:
  description: '# Introduction


    The Monoova PayTo API is designed to efficiently handle real time financial transactions, providing a reliable platform for creating payment agreements and initiating payments.'
  version: v1
  title: Monoova PayTo Manage Payment Agreements API
  contact:
    name: Monoova Support
    email: support@monoova.com
    url: https://www.monoova.com
  x-logo:
    url: https://movdpwebsiteprodae.blob.core.windows.net/images/Monoova-Primary-Logo-Black-RGB.png
    altText: Monoova logo
servers:
- url: https://api.monoova.com
  description: Production URL#
- url: https://sand-api.monoova.com
  description: Sandbox URL
security:
- BearerAuth: []
tags:
- name: Manage Payment Agreements
  description: Methods to handle the payment agreement lifecycle. There are 2 ways in which a payment agreement can be amended – unilaterally (no payer approval needed), and Bilaterally (payer approval required)
paths:
  /au/payto/pam-v1/PaymentAgreement:
    post:
      tags:
      - Manage Payment Agreements
      summary: Create a Payment Agreement
      description: 'The purpose of this endpoint is to create a payment agreement. An agreement can only initiate payments once the Payer approves it. Payers must respond by the respondByTime specified while creating the mandate. If respondByTime is not provided, it will be defaulted to 5 days for the Payer to approve or decline a payment agreement.


        Rate Limit

        Payment Agreement and Initiation endpoints have rate limits applied at a service level. If you process at volumes that surpass the rate limits, you will get a 429 HTTP status code for ''too many requests''. If you see this error, you will need to retry. If you experience this issue frequently, space out the calls. Alternatively, the Async endpoints have a much higher rate limit applied.


        A webhook will notify customers about the approval/declination of a payment agreement. There is also get payment agreement endpoints to check the status of the payment agreement.


        To receive payments in an account with Monoova, please create an automatcher account and use it under payee details when creating payment agreement. Automatcher accounts can also be created through the Sandbox Portal. Received payments through an automatcher account will be reported via webhook notification event name “PayToReceivePayment”.


        Additionally, sample test accounts will need to be used for the payer-consumer side of the mandate on Sandbox. Please find below sample test payer accounts: .tb { table-layout:auto; width:100px;!important } .td { overflow:hidden; white-space:nowrap; text-overflow:ellipsis!important}


        Account Name Monoova Sample 1 Monoova Sample 2 Monoova Sample 3 Monoova Sample 4 Monoova Sample 5


        BSB 802950


        Account Number 22090100


        PayID - Phone +61-422020901


        PayID - Email sample@monoova.com


        PayID - ABN 38126015228


        PayID - Organisation ID 987654321


        Below are a series of reference tables for the create and initiate payment agreement schemas


        Frequency

        .tb { table-layout:auto; width:100px;!important } .td { overflow:hidden; white-space:nowrap; text-overflow:ellipsis!important}


        Code Name Description


        ADHO Adhoc Event takes place on request or as necessary.


        DAIL Daily Event takes place every day.


        FRTN Fortnightly Event takes place every two weeks.


        INDA IntraDay Event takes place several times a day.


        MIAN SemiAnnual Event takes place every six months or two times a year.


        MNTH Monthly Event takes place every month or once a month.


        QURT Quarterly Event takes place every three months or four times a year.


        WEEK Weekly Event takes place once a week.


        YEAR Annual Event takes place every year or once a year.


        Agreement Type

        .tb { table-layout:auto; width:200px;!important } .td { overflow:hidden; white-space:nowrap; text-overflow:ellipsis!important}


        Code Name Description


        FIXE Fixed Payment amount is fixed.


        USGB UsageBased Payment amount is based on usage.


        VARI Variable Payment amount is variable.


        Agreement Type + Amount

        .tb { table-layout:auto; width:100px;!important } .td { overflow:hidden; white-space:nowrap; text-overflow:ellipsis!important}


        agreementType amount maximumAmount Rules


        FIXE Valid numeric value NA If Fixed, only amount should have values. Max amount should not be present


        USGB Valid numeric value Valid numeric value If Usage based, max amount is recommended. However, amount and max amount are optional. If both amount and max amount are present, amount should be less than max amount


        VARI Valid numeric value Valid numeric value If Variable, max amount is recommended. However, amount and max amount are optional. If both amount and max amount are present, amount should be less than max amount'
      operationId: post-paymentagreement
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePaymentAgreementDto'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreatePaymentAgreementResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pam-v1/paymentagreement/{paymentAgreementUID}/unilateral:
    patch:
      tags:
      - Manage Payment Agreements
      summary: Unilateral Amendment
      description: Unilateral changes to a payment agreement can be done without the payer’s approval. The only fields that can be changed unilaterally are the payee object and agreement descriptions.
      operationId: patch-paymentagreement-id-unilateral
      parameters:
      - name: paymentAgreementUID
        in: path
        required: true
        schema:
          type:
          - string
          - 'null'
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Za-z0-9_-]
          example: MONPAG12345
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/AmendUnilateralDetailsDto'
            example:
              description: payroll pag1
              shortDescription: payroll pag1
              payeeDetails:
                payeeType: ORGN
                payeeLinkedBsb: 802980
                payeeLinkedAccount: 33333333
                payeeLinkedPayId: abc@gmail.com
                payeeLinkedPayIdType: EMAIL
                payeeAccountName: PayCo
                ultimatePayee: PayCo
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmendUnilateralDetailsResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: b008558d-b6df-4935-b2aa-39b2f8d467be
                errors:
                - errorCode: PAM_BR_AMEND_FORBIDDEN
                  errorMessage: Can only amend payment agreement in active or paused status
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pam-v1/paymentagreement/{paymentAgreementUID}/bilateral:
    patch:
      tags:
      - Manage Payment Agreements
      summary: Bilateral Amendment
      operationId: patch-paymentagreement-id-bilateral
      description: Bilateral changes can't be done without the payer’s approval. Changes can be made to payment terms. Changes made using this end point will only get reflected after payer approves the change. Until new terms are approved, payment agreement will be active with its last approved terms.
      parameters:
      - name: paymentAgreementUID
        in: path
        required: true
        schema:
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Za-z0-9_-]
          example: MONPAG12345
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmendBilateralDetailsDto'
            example:
              automaticRenewal: false
              endDate: '2022-09-30'
              respondByTime: '2022-09-1T08:20:50.52Z'
              paymentTerms:
                numberOfTransactionsPermitted: 10
                frequency: MNTH
                amount: 10.0
                maximumAmount": 1000.0
                agreementType: VARI
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmendBilateralDetailsResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pam-v1/paymentagreement/{paymentAgreementUID}/status:
    patch:
      tags:
      - Manage Payment Agreements
      summary: Amend Payment Agreement Status
      description: 'This endpoint allows the initiator to change the status of a payment agreement. Available statuses are `active`, `pause`, or `cancel`.


        Status Reason Code


        .tb { table-layout:auto; width:200px;!important }

        .td { overflow:hidden; white-space:nowrap; text-overflow:ellipsis!important}


        Code Reason


        AC02Invalid Debtor Account Number


        AC04Closed Account Number


        AC05Closed Debtor Account Number


        AC06Blocked Account


        AC13Invalid Debtor Account Type


        AG01Transaction Forbidden


        AG03Transaction Not Supported


        AM03Not Allowed Currency


        AM12Invalid Amount


        AM14Amount Exceeds Agreed Limit


        CTAMContract Amended


        CTCAContract Cancellation Initiated By Debtor


        CTEXContract Expired


        MCFCPayment Agreement Suspended Final Collection


        MCOCPayment Agreement Suspended Once Off Collection


        MD07End Customer Deceased


        MD08No Payment Agreement Service By Agent


        MD09No Payment Agreement Service On Customer


        MD16Requested By Customer


        MD17Requested By Initiating Party


        MD20Payment Agreement Expired


        MD21Payment Agreement Cancelled Due To Fraud


        MS02Not Specified Reason Customer Generated


        MS03Not Specified Reason Agent Generated


        MSUCPayment Agreement Suspended 7 Consecutive Unsuccessful Collections


        NARRNarrative


        NOASNo Answer From Customer


        RR04Regulatory Reason


        SL01Specific Service Offered By Debtor Agent


        SL11Creditor Not On Whitelist Of Debtor


        SL12Creditor On Blacklist Of Debtor'
      operationId: patch-paymentagreement-id-status
      parameters:
      - name: paymentAgreementUID
        in: path
        required: true
        schema:
          type: string
          description: Id to uniquely identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Za-z0-9_-]{1,35}$
          example: MONPAG12345
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AmendPaymentAgreementStatusDto'
            example:
              statusChange: pause
              reasonCode: AC02
              reasonDescription: Amend mandate status
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AmendPaymentAgreementStatusResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pam-v1/paymentAgreement/{PaymentAgreementUID}/recall/{actionIdentification}:
    patch:
      tags:
      - Manage Payment Agreements
      summary: Recall a Payment Agreement
      description: The purpose of this operation is to recall a pending payment agreement before it is approved or declined by the payer servicer/customer.
      operationId: patch-paymentagreement-id-recall
      parameters:
      - name: PaymentAgreementUID
        in: path
        required: true
        schema:
          type: string
          maxLength: 35
          pattern: ^[A-Za-z0-9_-]
          description: Id to uniquely Identify a payment agreement.
          example: MONPAG12345
      - name: actionIdentification
        in: path
        required: true
        schema:
          type: string
          maxLength: 35
          pattern: ^[a-f0-9]{12}1[a-f0-9]{3}[89ab][a-f0-9]{15}$
          description: unique Id used to identify pending(unapproved) actions. This id is assigned when a new payment agreement is created or when a bilateral amendment is made.
          example: 6ae818a80bc362618aeaece46ee70e4a
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecallPaymentAgreementLastActionResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
components:
  schemas:
    PayerDetailsDto:
      type: object
      required:
      - payerType
      - payer
      - ultimatePayer
      - payerPartyReference
      oneOf:
      - required:
        - linkedBsb
        - linkedAccount
      - required:
        - linkedPayId
        - linkedPayIdType
      properties:
        payerType:
          type:
          - string
          - 'null'
          description: Identifies the type of party. </br> Possible Values - ORGN (Organization),    PERS (Person)
          example: ORGN
        linkedBsb:
          type:
          - string
          - 'null'
          description: BSB (Bank-State-Branch) number. </br>Required if 'linkedPayId' and 'linkedPayIdType' are not provided.
          example: 802950
        linkedAccount:
          type:
          - string
          - 'null'
          description: Bank account number. </br>Required if 'linkedPayId' and 'linkedPayIdType' are not provided.
          maxLength: 28
          example: 10109010
        linkedPayId:
          type:
          - string
          - 'null'
          example: null
          description: PayID. </br> Email, phone number, ABN, ACN or Organisation ID. </br>Required if 'linkedBsb' and 'linkedAccount' are not provided. <a href="/payTo#tag/PAYID-Format-Validation">See PAYID Format Validation.</a>
        linkedPayIdType:
          type:
          - string
          - 'null'
          example: null
          description: PayID Type. </br>Possible Values - Email, PhoneNumber, ABN, ACN, OrganisationId. </br>Required if 'linkedBsb' and 'linkedAccount' are not provided.
        payer:
          type:
          - string
          - 'null'
          description: Bank Account Name.
          maxLength: 140
          example: ABCCORPCo
        ultimatePayer:
          type:
          - string
          - 'null'
          maxLength: 140
          description: Name by which the party is known, and which is usually used to identify that party.
          example: ABCCORPCo
        payerPartyReference:
          type:
          - string
          - 'null'
          maxLength: 35
          description: This field will be presented to Payer in the detail agreement view. This field also be used group payment initiations associated with a payment agreement.
          example: Payer54321
      additionalProperties: false
    CreatePaymentAgreementResponse:
      type: object
      properties:
        traceId:
          type: string
          example: 1dabfaa9-abe8-4d2d-a69a-b723079d84ed
        paymentAgreementUID:
          type: string
          maxLength: 35
          pattern: ^[A-Za-z0-9_-]
          description: Id to uniquely Identify a payment agreement.
          example: BCORP123456
        PaymentAgreementStatus:
          type: string
          description: This is the status of the payment agreement. Status (e.g. Active, Cancelled, ...). See <a href="/payTo#tag/Payment-Agreement-Status">Payment Agreement Status</a> for all options.
          example: Created
        PaymentAgreementStatusDescription:
          type:
          - string
          - 'null'
          description: This describes the status. For example, a status of ‘created’ will have a description of ‘Pending Payer Approval’
          example: Pending Payer Approval
        mmsId:
          type: string
          description: This is the unique ID that identifies this payment agreement.
          example: a9ba56f64baa1dee9ac2d7f87c2621fa
        registrationDateTime:
          type: string
          description: The date and time that you created the mandate.
          example: 2022-09-05 05:29:53.031000+00:00
        actionIdentification:
          type: string
          example: b9c91b0f382b1fa5bf7e87aaad094eee
      additionalProperties: false
    AmendPaymentAgreementStatusDto:
      type: object
      properties:
        paymentAgreementUID:
          type: string
          description: 'Unique ID of the payment agreement.

            '
        statusChange:
          type: string
          description: The status that you wish to change the payment agreement to. </br> <strong> Note&#58;</strong> You cannot change a status from ‘Created’ to ‘Cancel’. If you wish to recall a payment agreement before the payer has approved it, you need to use the Recall Agreement endpoint.</b> </br> <style type="text/css"> .tb { table-layout:auto; width:300px;!important } .td { overflow:hidden; white-space:nowrap; text-overflow:ellipsis!important} </style> <table class="tb"> <tr> <th> Current Status </th> <th> Payload Status </th> <th> New Status </th> <th> Note </th> </tr> <tr><td>    Active    </td><td>    Cancel    </td> <td>    Cancelled    </td><td>    Reason Code is mandatory.    </td></tr> <tr><td>    Active     </td><td>    Pause    </td><td>    Paused    </td><td>    Reason Code is mandatory.    </td></tr> <tr><td>    Paused    </td><td>    Resume    </td><td>    Active    </td><td>    Only party who suspended can Activate payment agreement    </td></tr> <tr><td>    Paused    </td><td>    Cancel    </td><td>    Cancelled    </td><td>    Reason Code is mandatory.    </td></tr> <tr><td>    Cancel    </td><td>-</td><td>-</td><td>    This is the final status    </td></tr> </table>
        reasonCode:
          type: string
          description: 'Reason code for changing the agreement status. Must be provided when the status is `Cancel` or `Pause`.

            '
          example: AC02
        reasonDescription:
          type: string
          description: 'Description of the reason for the change in status.

            '
          example: Invalid Debtor Account Number
          maxLength: 256
    AmendBilateralDetailsDto:
      type: object
      properties:
        automaticRenewal:
          type:
          - boolean
          - 'null'
        endDate:
          type:
          - string
          - 'null'
          description: End date of the validity of the mandate. If specified, the mandate is valid until 23:59:59.999 Australia Sydney time on this date.
        respondByTime:
          type:
          - string
          - 'null'
          format: date-time
          description: Optional time used to indicate by when resolution of a bilateral action is requested from the other party to the payment agreement. It will be provided in any notification sent to the counterparty. This time is for informational purposes only and does not affect the expiry time imposed by the MMS. Must be future date and less than 5 days If not provided value will be defaulted to agreement creation datetime + 5 day Default time zone is UTC
        paymentTerms:
          $ref: '#/components/schemas/PaymentTermsDto'
      additionalProperties: false
    AmendUnilateralDetailsResponse:
      type: object
      properties:
        paymentAgreementUID:
          type: string
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Z0-9_-]
          example: BCORP1662358223
        traceId:
          type: string
          example: 1dabfaa9-abe8-4d2d-a69a-b723079d84ed
        mmsId:
          type: string
          description: This is the unique ID that identifies this payment agreement.
          example: aa0a5d7eedcd1c01999b2906b1edd8cd
        actionIdentification:
          type: string
          example: b9c91b0f382b1fa5bf7e87aaad094eee
      additionalProperties: false
    PaymentTermsDto:
      required:
      - numberOfTransactionsPermitted
      - frequency
      - amount
      - agreementType
      type: object
      properties:
        numberOfTransactionsPermitted:
          type:
          - integer
          - 'null'
          format: int32
          description: Quantifies the number of transactions allowed per frequency
          example: 10
        frequency:
          type:
          - string
          - 'null'
          description: Specifies the regularity of an event. See Frequency Table for allowed values
          example: WEEK
        pointInTime:
          type:
          - number
          - 'null'
          description: Qualifies the frequency in terms of an exact point in time or moment within the specified period.</br> Valid non decimal numeric value. Supported values will be 01 to 31 </br> This field works in combination with frequency and can only be provided when frequency = MNTH </br> This field should not be provided if numberOfTransactionsPermitted is provided
          example: null
        amount:
          type:
          - number
          - 'null'
          maxLength: 34
          example: null
          description: Exact amount that may be paid from the Creditor's account, per instruction. Refer to AgreementType & Amount table below
        maximumAmount:
          type:
          - number
          - 'null'
          maxLength: 34
          example: 100.0
          description: Maximum amount that may be paid from the Creditor's account, per instruction. Refer to AgreementType & Amount table below
        agreementType:
          type:
          - string
          - 'null'
          description: Based on the AgreementType table
          example: VARI
      additionalProperties: false
    AmendPaymentAgreementStatusResponse:
      type: object
      properties:
        traceId:
          type: string
          description: Trace ID for tracking the request.
        paymentAgreementUID:
          type: string
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Z0-9_-]
          example: MONPAG12345
        paymentAgreementStatus:
          type: string
          description: 'The current status of the payment agreement.

            '
          example: Paused
        paymentAgreementStatusDescription:
          type: string
          description: 'Detailed description of the current status.

            '
          example: Status changed from Active to Paused
        mmsId:
          type: string
          description: 'Unique ID that identifies this payment agreement within the system.

            '
    PaymentDetailsDto:
      required:
      - automaticRenewal
      - purpose
      - startDate
      properties:
        automaticRenewal:
          type:
          - boolean
          - 'null'
          example: false
          description: Determines if the payment agreement automatically renews at the end of the defined period. </br> Possible values - True, False </br> endDate cannot be present if automaticRenewal is set as 'TRUE', endDate must be present if automaticRenewal is set as 'FALSE'
        description:
          type:
          - string
          - 'null'
          description: Reason for the mandate setup as narrative text. </br> Either "description" or "short_description" must be present
          maxLength: 140
          example: null
        shortDescription:
          description: Reason for the mandate setup as narrative text. </br> Either "description" or "short_description" must be present
          type:
          - string
          - 'null'
          maxLength: 35
          example: PayToTest_001
        purpose:
          type:
          - string
          - 'null'
          description: Payment Purpose Code. </br>  Possible Values- </br>  MORT - Mortgage Payments </br>  UTIL - Utility Payments </br>  LOAN - Loan Payments </br>  DEPD - Dependant Support Payments </br>  GAMP - Gambling Payments </br>  RETL - Retail Payments </br>  SALA - Salary Payments </br>  PERS - Personal Payment </br>  GOVT - Government Payments </br>  PENS - Pension Payments </br>  TAXS - Tax Payments </br>  OTHR - Other Service Payments
          example: MORT
        respondByTime:
          type:
          - string
          - 'null'
          description: Optional time used to indicate by when resolution of a bilateral action is requested from the other party to the payment agreement. It will be provided in any notification sent to the counterparty. This time is for informational purposes only and does not affect the expiry time imposed by the MMS.<br/>Must be future date and less than 5 days<br/> If not provided value will be defaulted to agreement creation datetime + 5 day<br/> Default time zone is UTC
          format: ISODateTime ( yyyy-mm-ddThh:mm:ss+|–hh:mm)
          example: 2022-09-13 14:35:27+00:00
        startDate:
          description: Start date of the validity of the mandate. The mandate is valid as of 00:00:00.000 Australia Sydney time on this date.
          type:
          - string
          - 'null'
          format: YYYY-MM-DD
          example: 2022-09-13
        endDate:
          type:
          - string
          - 'null'
          format: YYYY-MM-DD
          example: 2023-08-24
          description: End date of the validity of the mandate. If specified, the mandate is valid until 23:59:59.999 Australia Sydney time on this date.
      additionalProperties: false
    PayeeDetailsDto:
      required:
      - payeeType
      oneOf:
      - required:
        - payeeLinkedBsb
        - payeeLinkedAccount
      - required:
        - payeeLinkedPayId
        - payeeLinkedPayIdType
        - payeeAccountName
      type: object
      properties:
        payeeType:
          type:
          - string
          - 'null'
          description: Identifies the type of a party.</br> Possible Values ORGN - Organization, PERS - Person
          example: ORGN
        payeeLinkedBsb:
          type:
          - string
          - 'null'
          description: BSB number. </br>Required if 'payeeLinkedPayId' and 'payeeLinkedPayIdType' are not provided. e.g. '999-999 or 999999'
          example: 999-999
        payeeLinkedAccount:
          type:
          - string
          - 'null'
          maxLength: 28
          description: Bank Account Number. </br>Required if 'payeeLinkedPayId' and 'payeeLinkedPayIdType' are not provided.
          example: 22222222
        payeeLinkedPayId:
          type:
          - string
          - 'null'
          description: PayID. </br> Email, phone number, ABN, ACN or Organisation name. </br>Required if 'payeeLinkedBsb' and 'payeeLinkedAccount' are not provided. <a href="/payTo#tag/PAYID-Format-Validation">See PAYID Format Validation.</a>
          example: ''
        payeeLinkedPayIdType:
          type:
          - string
          - 'null'
          description: PayID Type. Possible values ABN, Email, PhoneNumber, OrganisationId, ACN. </br>Required if 'payeeLinkedBsb' and 'payeeLinkedAccount' are not provided.
          example: ''
        payeeAccountName:
          type:
          - string
          - 'null'
          description: Bank Account Name </br> Can only provide payeeAccountName in the payload if crediting an external BSB. Mandatory if crediting a PayID.
          maxLength: 140
          example: ABCORP
        ultimatePayee:
          type:
          - string
          - 'null'
          example: ABCORP
          description: Name by which the party is known, and which is usually used to identify that party.</br> Can only provide ultimatePayee in the payload if crediting an external BSB.
      additionalProperties: false
    AmendBilateralDetailsResponse:
      type: object
      properties:
        paymentAgreementUID:
          type: string
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Z0-9_-]
          example: MONPAG12345
        mmsId:
          type: string
          description: This is the unique ID that identifies this payment agreement.
          example: 684211c8a4076eeea68e63eeaa8ea6aa
        actionIdentification:
          type: string
          example: eea687ee114eae368ca066aa62bae488
      additionalProperties: false
    AmendUnilateralDetailsDto:
      type: object
      properties:
        description:
          type:
          - string
          - 'null'
          description: Reason for the mandate setup as narrative text.</br> Either "description" or "short_description" must be present.
          maxLength: 140
          example: payroll pag1
        shortDescription:
          type:
          - string
          - 'null'
          description: Reason for the mandate setup as narrative text.</br> Either "description" or "short_description" must be present.
          maxLength: 35
          example: payroll pag1
        payeeDetails:
          $ref: '#/components/schemas/PayeeDetailsDto'
      additionalProperties: false
    CreatePaymentAgreementDto:
      type: object
      required:
      - paymentAgreementUID
      properties:
        paymentAgreementUID:
          type: string
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Z0-9_-]
          example: ABCORP123456
        payeeDetails:
          $ref: '#/components/schemas/PayeeDetailsDto'
        payerDetails:
          $ref: '#/components/schemas/PayerDetailsDto'
        paymentTerms:
          $ref: '#/components/schemas/PaymentTermsDto'
        paymentDetails:
          $ref: '#/components/schemas/PaymentDetailsDto'
      additionalProperties: false
    RecallPaymentAgreementLastActionResponse:
      type: object
      properties:
        paymentAgreementUID:
          type: string
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Z0-9_-]
          example: BCORP12345678
        mmsId:
          type: string
          description: This is the unique ID that identifies this payment agreement.
          example: cf9cba5ea20c1e6b87aa04cc8955abcc
        paymentAgreementStatus:
          type: string
          description: This is the status of the payment agreement.
          example: Cancelled
        paymentAgreementStatusDescription:
          type: string
          description: This describes the status. For example, a status of ‘created’ will have a description of ‘Pending Payer Approval’
          example: Mandate action recalled
        actionIdentification:
          type: string
          description: unique Id used to identify pending(unapproved) actions. This id is assigned when a new payment agreement is created or when a bilateral amendment is made.
          example: 6ae818d80ba362618a2aece46ee70e4a
      additionalProperties: false
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic
x-tagGroups:
- name: ''
  tags:
  - Generate a Bearer Token
  - Manage Payment Agreements
  - PayTo Async API
  - Initiate a Payment
  - Reporting
  - Webhooks
  - Notification Management
  - PAYID Format Validation
  - Client Error Responses
  - Monoova Error Codes
  - Mandate Status Reason Codes
  - Payment Initiation Status
  - Payment Agreement Status
  - Payment Initiation Reject Reason Codes
