openapi: 3.2.0
info:
  description: '# Introduction


    The Monoova PayTo API is designed to efficiently handle real time financial transactions, providing a reliable platform for creating payment agreements and initiating payments.'
  version: v1
  title: Monoova PayTo Reporting API
  contact:
    name: Monoova Support
    email: support@monoova.com
    url: https://www.monoova.com
  x-logo:
    url: https://movdpwebsiteprodae.blob.core.windows.net/images/Monoova-Primary-Logo-Black-RGB.png
    altText: Monoova logo
servers:
- url: https://api.monoova.com
  description: Production URL#
- url: https://sand-api.monoova.com
  description: Sandbox URL
security:
- BearerAuth: []
tags:
- name: Reporting
  description: 'PayTo Reporting


    A new report has been added specifically for NPP payments related to PayTo.'
paths:
  /au/payto/pam-v1/PaymentAgreement:
    get:
      tags:
      - Reporting
      summary: Get Payment Agreements by Date Range
      description: Previously created Payment Agreements can be retrieved individually date range.
      operationId: get-paymentagreement
      parameters:
      - name: createdStartDate
        in: query
        required: true
        description: Start Date. </br>Required. ISO8601 date-time
        schema:
          type: string
          format: date-time
      - name: pageNumber
        in: query
        description: Page to be returned after records are split as per pageSize. <br/> Optional, If not provided, it is defaulted to 1.
        schema:
          type: integer
          format: int32
      - name: pageSize
        in: query
        description: Number of records per page. </br> Optional, If not provided page size will be defaulted to 50. Maximum allowed value is 200.
        schema:
          type: integer
          format: int32
      - name: createdEndDate
        in: query
        description: End Date. Optional, if not provided it will be defaulted to createdStartDate +24 hours. ISO8601 date-time
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentAgreementsListResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pam-v1/paymentAgreement/{paymentAgreementUID}:
    get:
      tags:
      - Reporting
      summary: Get Payment Agreement by UniqueId
      operationId: get-paymentagreement-id
      description: Previously created Payment Agreements can be retrieved individually via uniqueId
      parameters:
      - name: paymentAgreementUID
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentAgreementResponse'
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: PAM_PAG_NOT_FOUND_ERROR
                  errorMessage: PaymentAgreement not found for PaymentAgreementUID 12345
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pas-v1/paymentInstruction:
    get:
      tags:
      - Reporting
      summary: Get Payment Instructions By Date Range
      description: Previously created Payment initiations can be retrieved individually via date range.
      operationId: get-paymentinstruction
      parameters:
      - name: createdStartDate
        in: query
        description: Required. Format - ISO8601 date-time.
        schema:
          type: string
          format: date-time
      - name: pageNumber
        description: Number of records per page </br> Optional, If not provided, value will be defaulted to 1.
        in: query
        schema:
          type: integer
          format: int32
      - name: pageSize
        in: query
        description: Number of records per page. </br> Optional, If not provided page size will be defaulted to 50. Maximum allowed value is 200.
        schema:
          type: integer
          format: int32
      - name: createdEndDate
        in: query
        description: Start Date. </br>Optional, if not provided it will be defaulted to createdStartDate.  ISO8601 date-time
        schema:
          type: string
          format: date-time
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentInitiationDetails:
                    type:
                    - array
                    - 'null'
                    items:
                      $ref: '#/components/schemas/PaymentStatusResponseDto'
                  traceId:
                    type:
                    - string
                    - 'null'
                    example: 7fcb7dc4-ab8d-4bc8-8fa8-1335172377e2
                additionalProperties: false
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: PaymentInstruction 12345 is not found
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
  /au/payto/pas-v1/paymentinstruction/{paymentInitiationUID}:
    get:
      tags:
      - Reporting
      summary: Get Payment Instruction By UniqueId
      description: Previously created Payment initiations can be retrieved individually via uniqueId.
      operationId: get-paymentinstruction-paymentinitiationid
      parameters:
      - name: paymentInitiationUID
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  paymentInitiationDetail:
                    $ref: '#/components/schemas/PaymentStatusResponseDto'
                  traceId:
                    type:
                    - string
                    - 'null'
                    example: 7fcb7dc4-ab8d-4bc8-8fa8-1335172377e2
                additionalProperties: false
        '400':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '403':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '404':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: PAS_INSTRUCTION_NOT_FOUND
                  errorMessage: PaymentInstruction 12345 is not found
        '500':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '502':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
        '504':
          description: Error
          content:
            application/json:
              example:
                traceId: f1a7fbd7-ca39-4b98-b247-f4e0e004f152
                errors:
                - errorCode: string
                  errorMessage: string
components:
  schemas:
    ActionDetails:
      type: object
      properties:
        actionId:
          type: string
          description: A unique identifier for the action.
          example: 45df1d4abc914455a0e377051cb39fd7
        actionType:
          type: string
          enum:
          - Create
          - Amend
          description: The type of action, which can be either 'Create' or 'Amend'.
        bilateral:
          type: boolean
          description: Indicates whether the action is bilateral.
          example: true
        status:
          type: string
          enum:
          - Completed
          - Cancelled
          - PendingApproval
          - Declined
          - Expired
          - Queued
          description: The current status of the action.
          example: PendingApproval
    PayeeDetailsResponseDto:
      type: object
      properties:
        payeeType:
          type: string
          description: Specifies whether the payee is an organization or an individual.
          example: null
        payeeLinkedBsb:
          type:
          - string
          - 'null'
          description: Bank State Branch (BSB) number identifying the bank branch of the payee.
          example: 802950
        payeeLinkedAccount:
          type:
          - string
          - 'null'
          description: Account number of the payee.
          example: 10109010
        payeeLinkedPayId:
          type:
          - string
          - 'null'
          description: PayID associated with the payee's account.
          example: null
        payeeLinkedPayIdType:
          type:
          - string
          - 'null'
          description: Type of PayID linked to the payee's account.
          example: null
        payeeAccountName:
          type:
          - string
          - 'null'
          description: Name associated with the payee's bank account.
          example: BCORP
        ultimatePayee:
          type: string
          description: The final recipient of the funds.
          example: BCORP
      additionalProperties: false
    PaymentAgreement:
      type: object
      properties:
        paymentAgreementUID:
          type:
          - string
          - 'null'
          description: A user-provided unique identifier for the payment agreement.
          example: BCORP1662344139
        paymentAgreementStatus:
          type:
          - string
          - 'null'
          description: Current status of the payment agreement. Status (e.g. Active, Cancelled, ...). See <a href="/payTo#tag/Payment-Agreement-Status">Payment Agreement Status</a> for all options.
          example: Paused
        statusReasonCode:
          type:
          - string
          - 'null'
          example: R006
        statusReasonDescription:
          type:
          - string
          - 'null'
          example: Account is now closed
        mmsId:
          type:
          - string
          - 'null'
          description: A unique identifier for the payment agreement.
          example: d6765e4ff2eb1e7f83d72c1f8d3e2a07
        payeeDetails:
          $ref: '#/components/schemas/PayeeDetailsResponseDto'
        payerDetails:
          $ref: '#/components/schemas/PayerDetailsResponseDto'
        paymentTerms:
          $ref: '#/components/schemas/PaymentTermsResponseDto'
        paymentDetails:
          $ref: '#/components/schemas/PaymentDetailsResponseDto'
        pendingActions:
          type: array
          items:
            $ref: '#/components/schemas/ActionDetails'
      additionalProperties: false
    PaymentAgreementsListResponse:
      type: object
      properties:
        paymentAgreementDetails:
          type: array
          items:
            $ref: '#/components/schemas/PaymentAgreement'
        traceId:
          type:
          - string
          - 'null'
          example: 7fcb7dc4-ab8d-4bc8-8fa8-1335172377e2
      additionalProperties: false
    PaymentStatusResponseDto:
      type: object
      properties:
        paymentAgreementUID:
          type: string
          description: Id to uniquely Identify a payment agreement.
          maxLength: 35
          pattern: ^[A-Z0-9_-]
          example: MONPAG12345
        paymentInitiationUID:
          type: string
          description: Id to uniquely Identify a payment initiation.
          maxLength: 35
          pattern: ^[A-Z0-9_-]
          example: TRANSACTIONREFERRENCE2345
        paymentInitiationStatus:
          type: string
          description: A valid <a href='/payTo#tag/Payment-Initiation-Status'>Payment Initiation Status</a>.
          example: ACSC
        paymentInitiationStatusDescription:
          type: string
          description: This describes the  paymentinitiationstatus.
          example: Accepted & Settled
        mmsId:
          type: string
          description: This is the unique ID that identifies this payment agreement.
          example: ed8569b4fd8616259d15bcb9a2da2bc0
        statusReasonCode:
          type:
          - string
          - 'null'
          example: R002
        statusReasonDescription:
          type:
          - string
          - 'null'
          example: Account to be debited does not exist
      additionalProperties: false
    PaymentTermsResponseDto:
      type: object
      properties:
        numberOfTransactionsPermitted:
          type: integer
          format: int32
          description: Specifies the maximum number of transactions allowed within the specified frequency period.
          example: 100
        frequency:
          type: string
          description: Defines how often transactions can occur
          example: WEEK
        amount:
          type:
          - number
          - 'null'
          format: double
          description: Fixed amount for transactions if applicable; null if variable amounts are allowed.
          example: null
        maximumAmount:
          type:
          - number
          - 'null'
          format: double
          description: The maximum allowable amount for a transaction under this agreement.
          example: 100.0
        agreementType:
          type: string
          description: Type of agreement, such as variable (VARI) or fixed, dictating how amounts and terms are treated.
          example: VARI
      additionalProperties: false
    PayerDetailsResponseDto:
      type: object
      properties:
        payerType:
          type: string
          description: Type of the payer entity, such as 'ORGN' for organization.
          example: ORGN
        linkedBsb:
          type:
          - string
          - 'null'
          description: BSB number associated with the payer’s bank account.
          example: 802950
        linkedAccount:
          type:
          - string
          - 'null'
          description: Bank account number of the payer.
          example: 10109010
        linkedPayId:
          type:
          - string
          - 'null'
          description: PayID linked to the payer’s account, may be null if not used.
          example: null
        linkedPayIdType:
          type:
          - string
          - 'null'
          description: Type of the linked PayID, such as 'Email' or 'Phone', may be null if PayID is not used.
          example: null
        payer:
          type: string
          description: Name of the payer.
          example: WidgetCo
        ultimatePayer:
          type: string
          description: The final entity responsible for making the payment.
          example: WidgetCo
        payerPartyReference:
          type: string
          description: A reference identifier provided by the payer.
          example: Payer1662333659
      additionalProperties: false
    PaymentDetailsResponseDto:
      type: object
      properties:
        automaticRenewal:
          type: boolean
          description: Indicates if the agreement renews automatically
          example: false
        description:
          type: string
          description: Detailed reason for the mandate
          example: payroll pag
        shortDescription:
          type: string
          description: Brief reason for the mandate
          example: PayToTest_1662333659
        purpose:
          type: string
          description: Code indicating the payment's purpose.
          example: MORT
        respondByTime:
          type: string
          description: Time by which a response is needed.
          example: 2022-10-07 14:35:27-10:00
        startDate:
          type: string
          description: Start date of the mandate's validity.
          example: 2022-09-05
        endDate:
          type: string
          description: End date of the mandate's validity.
          example: 2023-08-24
      additionalProperties: false
    PaymentAgreementResponse:
      type: object
      properties:
        traceId:
          type: string
          example: 43075658-ed9a-4ce0-84ba-2f6524a16676
        paymentAgreementDetails:
          $ref: '#/components/schemas/PaymentAgreement'
      additionalProperties: false
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      type: http
      scheme: basic
x-tagGroups:
- name: ''
  tags:
  - Generate a Bearer Token
  - Manage Payment Agreements
  - PayTo Async API
  - Initiate a Payment
  - Reporting
  - Webhooks
  - Notification Management
  - PAYID Format Validation
  - Client Error Responses
  - Monoova Error Codes
  - Mandate Status Reason Codes
  - Payment Initiation Status
  - Payment Agreement Status
  - Payment Initiation Reject Reason Codes
